export interface SkillGroup {
  id: string
  title: string
  namespace: string
  accent: 'amber' | 'purple' | 'teal'
  skills: string[]
}

export const skillGroups: SkillGroup[] = [
  {
    id: 'languages',
    title: 'Languages',
    namespace: 'core_lang',
    accent: 'amber',
    skills: ['Python', 'Java', 'C++', 'JavaScript', 'Bash'],
  },
  {
    id: 'ml-deep-learning',
    title: 'Machine Learning & Deep Learning',
    namespace: 'ml_systems',
    accent: 'purple',
    skills: [
      'Supervised ML',
      'Unsupervised ML',
      'Neural Networks',
      'Transformers',
      'LLMs',
      'Vector Databases',
      'Semantic Search',
      'Embedding Models',
      'Graph Neural Networks',
      'Prompt Engineering',
      'RAG Pipelines',
      'Multi-Agent Systems',
      'LangGraph',
      'Model Evaluation',
      'Explainability',
    ],
  },
  {
    id: 'llm-ai-tools',
    title: 'LLM & AI Tools',
    namespace: 'rag_agents',
    accent: 'teal',
    skills: [
      'LangChain',
      'LangGraph',
      'Langfuse',
      'Pinecone',
      'FAISS',
      'Vector Indexing',
      'RAG Optimization',
      'Hybrid Search',
      'Semantic Routing',
      'OpenAI',
      'Azure AI',
      'Llama',
      'Cloud-Agnostic AI Development',
      'S3 Lifecycle Policies',
      'SSM',
      'CloudWatch',
      'SNS/SQS',
    ],
  },
  {
    id: 'cloud-mlops',
    title: 'Cloud & MLOps',
    namespace: 'infra_ops',
    accent: 'amber',
    skills: [
      'AWS Lambda',
      'AWS Fargate',
      'Amazon S3',
      'API Gateway',
      'CloudWatch',
      'Azure',
      'GCP',
      'Serverless',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'GitHub Actions',
      'Jenkins',
      'Cloud-Native Architectures',
      'Observability & Monitoring',
      'SCPs',
      'Aurora Serverless v2',
    ],
  },
  {
    id: 'data-engineering',
    title: 'Data Engineering & Databases',
    namespace: 'data_plane',
    accent: 'teal',
    skills: [
      'PostgreSQL',
      'pgvector',
      'Neo4j',
      'MongoDB',
      'Redis Caching',
      'Streamlit',
      'N8N Automation',
      'ETL Pipelines',
      'Web Scraping',
      'API Integrations',
      'Holoviews',
    ],
  },
  {
    id: 'frameworks-libraries',
    title: 'Frameworks & Libraries',
    namespace: 'model_libs',
    accent: 'purple',
    skills: [
      'PyTorch',
      'TensorFlow',
      'Keras',
      'scikit-learn',
      'HuggingFace',
      'Pandas',
      'NumPy',
      'OpenCV',
      'Seaborn',
      'Matplotlib',
      'Terraform',
    ],
  },
  {
    id: 'tools-platforms',
    title: 'Tools & Platforms',
    namespace: 'workbench',
    accent: 'amber',
    skills: ['Git', 'GitHub', 'VSCode', 'Jupyter', 'Holoviews', 'Selenium', 'Model Context Protocol'],
  },
  {
    id: 'core-technologies',
    title: 'Core Technologies',
    namespace: 'systems_ready',
    accent: 'teal',
    skills: [
      'AI System Design',
      'Production ML',
      'Cloud-Agnostic Architectures',
      'Data Modeling',
      'Prompt Optimization',
      'Latency Reduction',
      'High-Availability Systems',
      'Compliance-Aware Logging',
      'FERPA/HIPAA',
      'Technical Documentation',
      'API Design',
      'Code Reviews',
      'Testing Techniques',
    ],
  },
]

export const skillComments: Record<string, string> = {
  LangGraph: '// agent orchestration',
  Pinecone: '// vector retrieval',
  Terraform: '// repeatable infrastructure',
  Neo4j: '// graph reasoning',
  Langfuse: '// LLM observability',
  'AWS Lambda': '// serverless execution',
}

export const defaultSkillComment = '// used in production AI systems'
